### ISSUE TITLE
Refactor Code generation into a Model/View-esque strategy

### ISSUE THREAD

**Issue by jamesbascle** [Jagged/OneOf#14]
The code generation code has gotten extremely prickly.  I propose that we create a new assembly (let's call it OoModel for now) that we can reference from our .tt files.

OoModel will not be part of our deployable package - we will still be able to distribute OneOf as 1 .dll.

OoModel  will be something like the Model layer of an MVC/MVVM app in which we generate objects that contain the various properties that we need to render to the various bits of the OneOf, OneOfMatcher, OneOfSwitcher, etc. instead of being a fully procedural loop/text concatenation method we have now.

This will also allow us to break out the .TT file into multiple files, while re-using some of the other objects/methods like the indenter, the generic parameter generator, and other such niceties.

Thoughts?

**Comment by Jagged** [comment]
If I get you right, ultimately you'd like to do the core of the template coding outside of t4?  Heck, following that line of thought we could look at entirely different ways of generating the code.  How good is your CIL emit-foo? =)

Btw, t4 templates can include other t4 files for code reuse.  But you probably knew that.

**Comment by jamesbascle** [comment]
Well, if I can come up with some object model that represents the classes to be generated, moving the code generation to some other method becomes a matter of swapping out the T4 "view" to a CIL "view".  So I'd say it's still potentially the right way to go.

**Comment by jamesbascle** [comment]
I'd say i'm pretty much done on this matter after merge.

**Comment by Jagged** [comment]
That's awesome James, I'll commit it as soon as I can get my hands on my
computer.

I was thinking about the unit testing code which I have made nigh on
impossible to understand, all in the aim to get the magic 100% coverage,
which is pointless as the generated code only needs testing once given it
is identical for all arities. I'm gonna revert back to non reflection code
in the tests, they should always be easy to read, otherwise now we have to
test the tests! My bad!

On 26/10/2017 19:41, "jamesbascle" <notifications@github.com> wrote:

I'd say i'm pretty much done on this matter after merge.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Jagged/OneOf/issues/14#issuecomment-339567144>, or mute
the thread

**Comment by jamesbascle** [comment]
No problem, thanks! I think that's a great point actually.

**Comment by jamesbascle** [comment]
Done and done, 1.0.0.0 is released!
