### ISSUE TITLE
.Net Core

### ISSUE THREAD

**Issue by Jagged** [Jagged/OneOf#9]
@jamesbascle , 

I see Harry had dropped portable in favor of .Net core.  That does seem to be the way forward, but MS has been changing their mind seemingly weekly.  

Thoughts?

**Comment by jamesbascle** [comment]
The way forward seems to be the .NET standard thing.  I'm in no rush to change, so I'd say let's wait until they show commitment with release of Standard 2.0, then do it.

**Comment by Jagged** [comment]
What's disappointing with both .Net Portable and .Net Standard is their lack of support for .Net 4.0, something I'm stuck with thanks to having XP boxes dotted around the business.  So I can't actually use OneOf presently.  

We could always switch the project to a vanilla non-portable DLL, which would be usable on .Net 4.0 and above.  It just wouldn't be usable on Windows Phones or Silverlight, things that are both rather dead/dying.

Thoughts?

**Comment by Jagged** [comment]
I've made a multi-target nuget project in the past, using a batch file to help with the release process to ensure everything is built correctly, pass unit tests and then uploads to nuget.org.  I think I've still got the code around somewhere.  It ends up being a single nuget package with multiple targets within, driven from a single .csproj if memory serves, using multiple configurations to drive the target settings for .Net 4, .Net 4.6 etc.  

I'll have a look for the old project to see what I can scrounge up...

**Comment by Jagged** [comment]
I've made it so one solution hosts the building of both .Net 4.0 and Portable.  I had a go a changing Portable to NetStandard, and, well, after countless meaningless errors I gave up.  I know it must be doable, but I've spent enough time on it today.

**Comment by Jagged** [comment]
Finally got dual builds for .Net 4 and .Net Standard working from the same directory, see https://github.com/Jagged/OneOf/commit/fd75f364c2c6a3e346a6bcada26fd0decda3ac11 .

@jamesbascle , could you please confirm you are able to use the new version in your project OK?

**Comment by jamesbascle** [comment]
Will try to do that this coming weekend.  Been swamped past couple of weeks.

**Comment by jamesbascle** [comment]
Okay, I finally got around to this.  I upgraded it to a .NET Standard assembly instead of a PCL.

Check my commit found here: https://github.com/jamesbascle/OneOf/commit/8c51c7672f8036b4a1a55f6ce843e02377b9c00c

I also worked on speed a bit.  Here are some benchmarks of some various approaches I took that worked, with some asides on those that didn't.

First, the original:
old

Ctor1 ... 33.32M per second
Ctor5 ... 28.33M per second
Ctor9 ... 41.16M per second
Ctor11 ... 2.82M per second
Ctor15 ... 2.79M per second
Ctor19 ... 2.86M per second
Match1 ... 9.99M per second
Match5 ... 9.60M per second
Match9 ... 8.85M per second
Match11 ... 8.87M per second
Match15 ... 8.83M per second
Match19 ... 8.82M per second

The first approach I tried was my original dynamic approach with a Type to Type dictionary cache, because I found some corner cases that may not work properly with an interface that is orthogonal to the classes or their hierarchy. Due to a number of issues with this approach, I pursued other avenues, but decided that ultimately I would accept that as a fact of life for the moment - the best match method may need to be modified some to support that use case, or we can excise the ability to use interfaces altogether.

Next, I tried caching the type operations in the constructor with two approaches, with the ReadWriteLockSlim and a Dictionary, and a ConcurrentDictionary. The ConcurrentDictionary won out in numerous tests.  It also slowed down the types which matched immediately via the old switch statement, so I defaulted to the old switch statement way of doing it for the direct classes.  

hybrid - slim

Ctor1 ... 34.58M per second
Ctor5 ... 37.95M per second
Ctor9 ... 49.86M per second
Ctor11 ... 11.64M per second
Ctor15 ... 11.40M per second
Ctor19 ... 11.64M per second
Match1 ... 10.11M per second
Match5 ... 9.54M per second
Match9 ... 8.87M per second
Match11 ... 9.04M per second
Match15 ... 8.93M per second
Match19 ... 8.97M per second

hybrid - concurrent

Ctor1 ... 33.65M per second
Ctor5 ... 38.50M per second
Ctor9 ... 50.55M per second
Ctor11 ... 17.20M per second
Ctor15 ... 17.17M per second
Ctor19 ... 17.01M per second
Match1 ... 9.81M per second
Match5 ... 9.68M per second
Match9 ... 8.67M per second
Match11 ... 8.73M per second
Match15 ... 8.73M per second
Match19 ... 8.68M per second

After that, I decided that I wanted to get rid of the big switch statement method, and make it easier to help the compiler and JITter optimize the code.  For that purpose, I decided to try an approach I tried a long time ago, embedding the type information in the implicit conversion operator methods, and in the constructors, new ones of which were created for that purpose, along with a new backwards API-compatible OneOf(object o) signature - it does come at the cost of speed for that one signature only - though I've half a mind to remove it altogether since I think it doesn't actually make any semantic sense unless you're already in a type-unsafe world, which is potentially okay.

hybrid - concurrent - with constructor type shortcut

Ctor1 ... 55.52M per second
Ctor5 ... 63.62M per second
Ctor9 ... 64.04M per second
Ctor11 ... 22.39M per second
Ctor15 ... 21.88M per second
Ctor19 ... 22.25M per second
Match1 ... 9.99M per second
Match5 ... 9.36M per second
Match9 ... 8.81M per second
Match11 ... 8.75M per second
Match15 ... 8.81M per second
Match19 ... 8.73M per second


As you can see, this ends up with a ~2x improvement in the normal cases' OneOf creation times, and a ~10x improvement in the subclass case's creation times, with a negligible to none change in match times.

Ctor1 ... 53.34M per second
Ctor5 ... 63.05M per second
Ctor9 ... 64.03M per second
Ctor11 ... 22.25M per second
Ctor15 ... 22.26M per second
Ctor19 ... 22.27M per second
Match1 ... 9.88M per second
Match5 ... 9.57M per second
Match9 ... 8.85M per second
Match11 ... 8.88M per second
Match15 ... 8.83M per second
Match19 ... 8.84M per second

Press any key to end.
